backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: src/assets/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "About Text", name: "aboutTitle", widget: "string" }

          - { label: "About Body", name: "aboutText", widget: "string" }

          - label: "Product List"
            name: "products"
            widget: list
            fields:
              - { label: "Product Name", name: "name", widget: "string" }
              - {
                  label: "Product Description",
                  name: "description",
                  widget: "text",
                }
              - {
                  label: "Product Image",
                  name: "image",
                  widget: "image",
                  choose_url: true,
                  allow_multiple: false,
                }
